config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'home#index'
  resources :authorized_clients
  get 'set_cookie_client_secret/:id', to: 'authorized_clients#set_cookie_client_secret', as: :set_cookie
  resources :attendance
  post 'new_attendance', to: 'attendance#attend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveStorageSupport::SupportForBase64
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  self.table_name = 'attendance'
  require 'aws-sdk'
  require 'dotenv'
  Dotenv.load

  has_one_base64_attached :snapshot
  belongs_to :authorized_client, optional: true
  belongs_to :topican, optional: true

  def recognize

  end
end

app/models/authorized_client.rb
class AuthorizedClient < ApplicationRecord
  require 'securerandom'

  self.table_name = 'authorized_client'

  def self.generate_client_secret
    SecureRandom.base64(64)
  end
end

app/models/constants.rb
module Constants
  FACE_COLLECTION = 'facepica'
end

app/models/topican.rb
class Topican < ApplicationRecord
  self.table_name = 'topican'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable,
  # :recoverable, :rememberable
  devise :database_authenticatable, :validatable, :rememberable, :registerable

  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/attendance_controller.rb
# frozen_string_literal: true

class AttendanceController < HomeController
  include Constants
  before_action :client_initialied!, only: [:new]

  def new; end

  def attend
    @record = Attendance.new
    @record.snapshot.attach(data: params[:image])
    @record.topican = nil
    @record.authorized_client = nil

    ## Todo call to AWS Rekognition
    # content_type :json
    client = Aws::Rekognition::Client.new
    # Aws.config.update(
    #   region: 'us-east-1',
    #   credentials: Aws::Credentials.new(ENV['AWS_KEY'], ENV['AWS_SECRET'])
    # )
    response = client.search_faces_by_image(
      collection_id: Constants::FACE_COLLECTION,
      max_faces: 1,
      face_match_threshold: 95,
      image: {
        bytes: params[:image]
      }
    )
    if response.face_matches.count > 1
      { message: 'Too many faces found' }.to_json
    elsif response.face_matches.count == 0
      { message: 'No face detected!' }.to_json
    else
      # "Comparison finished - detected #{ response.face_matches[0].face.external_image_id } with #{ response.face_matches[0].face.confidence } accuracy."
      { id: response.face_matches[0].face.external_image_id, confidence: response.face_matches[0].face.confidence, message: 'Face found!' }.to_json
    end
  end

  def client_initialied!
    @client_secret = cookies[:client_secret]
    if @client_secret.nil?
      if current_user.nil?
        redirect_to new_user_session_path
      else
        redirect_to new_authorized_client_path
      end
    end
  end
end

app/controllers/authorized_clients_controller.rb
class AuthorizedClientsController < ApplicationController
  require 'json'
  before_action :authenticate_user!
  before_action :set_authorized_client, only: [:show, :edit, :update, :destroy, :set_cookie_client_secret]
  # after_action :after_save, only: [:update, :create]
  # GET /authorized_clients
  # GET /authorized_clients.json
  def index
    @authorized_clients = AuthorizedClient.all
  end

  # GET /authorized_clients/1
  # GET /authorized_clients/1.json
  def show
  end

  # GET /authorized_clients/new
  def new
    @authorized_client = AuthorizedClient.new
    @authorized_client.client_secret = AuthorizedClient.generate_client_secret
  end

  # GET /authorized_clients/1/edit
  def edit
  end

  # POST /authorized_clients
  # POST /authorized_clients.json
  def create
    @authorized_client = AuthorizedClient.new(authorized_client_params)

    respond_to do |format|
      if @authorized_client.save
        format.html {redirect_to @authorized_client, notice: 'Authorized client was successfully created.'}
        format.json {render :show, status: :created, location: @authorized_client}
      else
        format.html {render :new}
        format.json {render json: @authorized_client.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /authorized_clients/1
  # PATCH/PUT /authorized_clients/1.json
  def update
    respond_to do |format|
      if @authorized_client.update(authorized_client_params)
        format.html {redirect_to @authorized_client, notice: 'Authorized client was successfully updated.'}
        format.json {render :show, status: :ok, location: @authorized_client}
      else
        format.html {render :edit}
        format.json {render json: @authorized_client.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /authorized_clients/1
  # DELETE /authorized_clients/1.json
  def destroy
    @authorized_client.destroy
    respond_to do |format|
      format.html {redirect_to authorized_clients_url, notice: 'Authorized client was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def set_cookie_client_secret
    cookies.permanent[:client_secret] = @authorized_client.client_secret
    flash[:notice] = 'Set cookie successfully'
    # render :nothing => true
    # redirect_to authorized_clients_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_authorized_client
    @authorized_client = AuthorizedClient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def authorized_client_params
    params.require(:authorized_client).permit(:client_name, :client_secret, :location)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # require 'json'

  # before_action :client_initialied!

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorized_clients_helper.rb
module AuthorizedClientsHelper
  # def set_cookie_client_secret
  #   cookies.permanent[:client_secret] = @authorized_client.client_secret
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendance/new.html.erb
<h1>Facepica - Topican Attendance Management</h1>
<div>
  <video id="camera" width="640" height="480" autoplay></video>
</div>

<p>
  <button id='attend'>Compare Image</button>
</p>

<div>
  <canvas id="canvas" width="640" height="480"></canvas>
</div>

<div>
  <%# image_tag %>
</div>
<!--<div>-->
<!--  <br>-->
<!--  <input id='photo_id' placeholder='Enter name for photo' type='text'>-->
<!--  <button id='add_to_collection'>Add To Collection</button>-->
<!--  <br>-->
<!--</div>-->

<div id='upload_status'></div>
<div id='upload_result'></div>
<br>
<%= image_tag image_url('loading.gif'), height: '100', width: '100', id: 'loading_img' %>
<!--<img height='100' id='loading_img' src='/assets/images/loading.gif' width='100'>-->
<audio id='audio_speech' src='#'></audio>
<br>
<br>
<p>
  <a href="/collection/create">Create Collection</a> | <a href="/collection/delete">Delete Collection</a>
</p>
<!--<script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
<!--<script src="js/faceapp.js" type="text/javascript"></script>-->

app/views/authorized_clients/_form.html.erb
<%= form_with(model: authorized_client, local: true) do |form| %>
  <% if authorized_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authorized_client.errors.count, "error") %> prohibited this authorized_client from being saved:</h2>

      <ul>
      <% authorized_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :client_secret %>
    <%= form.text_area :client_secret, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authorized_clients/edit.html.erb
<h1>Editing Authorized Client</h1>

<%= render 'form', authorized_client: @authorized_client %>

<%= link_to 'Show', @authorized_client %> |
<%= link_to 'Back', authorized_clients_path %>

app/views/authorized_clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authorized Clients</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Client secret</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authorized_clients.each do |authorized_client| %>
      <tr>
        <td><%= authorized_client.client_name %></td>
        <td><%= authorized_client.client_secret %></td>
        <td><%= authorized_client.location %></td>
        <td><%= link_to 'Show', authorized_client %></td>
        <td><%= link_to 'Edit', edit_authorized_client_path(authorized_client) %></td>
        <td><%= link_to 'Destroy', authorized_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Set Cookie', set_cookie_path(authorized_client) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authorized Client', new_authorized_client_path %>

app/views/authorized_clients/new.html.erb
<h1>New Authorized Client</h1>

<%= render 'form', authorized_client: @authorized_client %>

<%= link_to 'Back', authorized_clients_path %>

app/views/authorized_clients/set_cookie_client_secret.html.erb
<h1>Set cookie completed successfully!</h1>

app/views/authorized_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @authorized_client.client_name %>
</p>

<p>
  <strong>Client secret:</strong>
  <%= @authorized_client.client_secret %>
</p>

<p>
  <strong>Location:</strong>
  <%= @authorized_client.location %>
</p>

<%= link_to 'Edit', edit_authorized_client_path(@authorized_client) %> |
<%= link_to 'Back', authorized_clients_path %>

app/views/home/index.html.erb
<!--<h1>Topica AI-based attendance system</h1>-->
<h1>AI-based attendance system</h1>
<div>
  <%= link_to "Setup device", new_authorized_client_path %> | <%= link_to "Attendance", new_attendance_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facepica</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
</html>